service: database
frameworkVersion: '3'

provider:
  name: aws

resources:
  Resources:
    products:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: products
  Outputs:
    TableName:
      Value: !Ref products